### ISSUE TITLE
refactor suspend/resume

### ISSUE THREAD

**Issue by slingamn** [ergochat/readline#15]
This code is extremely bogus:

https://github.com/ergochat/readline/blob/cd7fbcc32bc9f89efc0bb7baf55abbfe86c9c5ea/utils.go#L60-L83

Instead, resumption should be detected by handling SIGCONT. (Not sure about the story on Windows.)

**Comment by wader** [comment]
Related https://github.com/chzyer/readline/pull/48, but don't see if the bogus code is some windows workaround or not, there is specific "supports windows" commit in the PR

**Comment by slingamn** [comment]
Hmm. I tested on Windows and Ctrl-Z doesn't work at all (it leaves the terminal in a broken state, but doesn't suspend the process).

I found a [forum thread](https://ss64.org/viewtopic.php?t=135) saying that the Windows equivalent is Ctrl-S? But I'm not sure that this functionality actually exists on Windows.

**Comment by wader** [comment]
Ok sorry i know more or less nothing about windows terminals :( just got a little curious why such a function would be needed

**Comment by slingamn** [comment]
Ah, no problem :-) I think e32441ebb791044688b7b3ec7bff99e6b24d9fe1 means "fix compilation on Windows", not "fix the actual functionality on Windows".

**Comment by wader** [comment]
Aha :)

**Comment by GuillermoMajano** [comment]
hey bro, i see redundant code in this function.

**Comment by slingamn** [comment]
Done in #16
