### ISSUE TITLE
second pass at shrinking the API

### ISSUE THREAD

**Issue by slingamn** [ergochat/readline#27]
This is looking better:

https://pkg.go.dev/github.com/ergochat/readline@v0.0.3

but there's still a lot of cruft. For example:

1. `Listener` should probably become a function pointer type rather than an interface, eliminating the need for `DumpListener`. See #6 for discussion of the listener API
2. The relationship between `PrefixCompleter`, `PrefixCompleterInterface`, and functions like `Do` and `Print` is confused
3. `Instance` has too many methods
4. `Painter` should be a function pointer type, not an interface type
5. `TabCompleter` should probably be hidden
6. What are `SegmentComplete` and `SegmentCompleter`?

**Comment by slingamn** [comment]
What is `(Config).UniqueEditLine`?

**Comment by slingamn** [comment]
Effectively resolved by 0.1.0

**Comment by wader** [comment]
Thanks for all the work on this!
