### ISSUE TITLE
Typing beyond screen bounds and then erasing jumps up one line too far on Windows

### ISSUE THREAD

**Issue by Cynosphere** [ergochat/readline#35]
Tested on WezTerm, Windows Terminal (both use OpenConsole) and normal Command Prompt. WSL has normal expected Linux behavior.

**Comment by wader** [comment]
Hi, maybe you want to give this fork a try https://github.com/ergochat/readline is has quite a bit of fixes like this

**Comment by Cynosphere** [comment]
That's the repo we're currently on lol

**Comment by wader** [comment]
Sorry for the confusion! somehow just assumed this was for https://github.com/chzyer/readline 😬 😄

**Comment by slingamn** [comment]
62572843e9dec59d9d3b0e8caf4e5f2ae4656842 seems to fix this, but why? I'm unclear on why it was ever necessary to special-case Windows here. (It seems probable that #2 made a difference here.)
