### ISSUE TITLE
Where is the ClearScreen method?

### ISSUE THREAD

**Issue by dominikschulz** [ergochat/readline#36]
We are trying to migrate from chzyer/readline to this fork since the former seems to be unmaintained.
But I'm facing a few issues.

github.com/chzyer/readline had a [ClearScreen](https://pkg.go.dev/github.com/chzyer/readline?utm_source=godoc#ClearScreen) method that was quite convenient for us as we want to expose
users a way to clear the screen by typing `clear`. This package can still do that when pressing Ctrl+L but doesn't espose that as one easy method.

Could we get a ClearScreen method exposed, please?

**Comment by slingamn** [comment]
Thanks for your interest in the project! I'm working on this now, I should have an update in a day or two.

**Comment by dominikschulz** [comment]
Thanks a lot. Much appreciated!
