### ISSUE TITLE
option-left / alt-left should skip between words

### ISSUE THREAD

**Issue by slingamn** [ergochat/readline#59]
As discussed here: https://github.com/wader/fq/issues/940 this is a normal readline feature. I checked our v0.0.1 (last upstream release) and it does not work there, so it's not a regression, it was never implemented.

**Comment by wader** [comment]
Sorry i was confused about keys, it't not cmd+left/right, it's alt+left/right. For me it stopped working after  727da2a2231ae69efc612dbf52ac5033bccc0109, maybe we're testing differently? i'm using iterm2 on macOS.
Looking at the default profile key setting it says:
alt+left sends ^[b
alt+right send ^[f

Maps quite well to what was removed here https://github.com/ergochat/readline/commit/727da2a2231ae69efc612dbf52ac5033bccc0109#diff-8b7f25bac2ae04c2ce2abb628c6aa28103fd113103a62f3e9d232fa995684915L174 got lost in the refactor somehow?

**Comment by slingamn** [comment]
Hmm, that makes sense. I was testing on Linux, not MacOS --- I'll try it in iterm2 when I get a chance. (Alt-Left and Alt-Right work for me with GNU Readline in the same Linux terminal, e.g. with the CPython REPL, but they do not work with v0.0.1.)

**Comment by wader** [comment]
Tried hackily to add this in consumeANSIEscape
```
	switch initial {
	case 'f':
		return readResult{r: MetaForward, ok: true}, nil
	case 'b':
		return readResult{r: MetaBackward, ok: true}, nil
	}
```
seems to work but i'm a bit unsure how to refactor/restructure things to make do it in a sane way

**Comment by slingamn** [comment]
Just clarifying, the sequence is the ANSI escape `\x1b` followed immediately by `b` or `f`, and that's the whole sequence?

**Comment by wader** [comment]
Yeap i think so

**Comment by wader** [comment]
Got annoyed with this again today 😬 any suggestion how to fix? my change felt a bit too hacky

**Comment by slingamn** [comment]
Sorry about the delay. Your implementation strategy looks fine to me :-) I pushed a version of it here:

* https://github.com/ergochat/readline/tree/metaforward
* https://github.com/ergochat/readline/commit/e9aabe51db1baeff3e2cd091519ac64fb25e0992

It did not work for me in iTerm2 3.5.2 with default settings. Here are the keybindings I see with default settings:

![screenshot](https://github.com/ergochat/readline/assets/376448/2036ca17-2b08-44f0-8fd1-1453cfb1f1d3)

According to this, option-right would actually send `\x1b\x1b[C`, which is consistent with what I see in iTerm2 before and after this patch (option-right prints `[C`).

I implemented a hack to read sequences of this form and it works for me in iTerm2 and also on Linux with urxvt, although I haven't tested other Linux terminals yet.

What I would really like is some documentation about these sequences and also more clarity about sequences that start with a double `\x1b`. As it is, the patch linked above is safe to merge (it shouldn't break any existing functionality) but I don't feel like I can changelog it as "option-left now skips between words on MacOS", since it didn't actually work in my iTerm2 :-)

**Comment by slingamn** [comment]
I found a project dealing with a similar issue, although it didn't clarify things to my satisfaction: https://github.com/c-bata/go-prompt/issues/63#issuecomment-376439020

**Comment by slingamn** [comment]
More links:

* https://github.com/nodejs/node/issues/8934
* https://gitlab.com/gnachman/iterm2/-/issues/5451

**Comment by slingamn** [comment]
It looks like the "Natural text editing" presets in iTerm2 enable the short sequences `\x1bb` and `\x1bf`? So https://github.com/ergochat/readline/commit/e9aabe51db1baeff3e2cd091519ac64fb25e0992 seems OK to merge then, although it might be nice to fix this on Linux as well for parity with GNU Readline.

**Comment by slingamn** [comment]
GNU Readline also accepts Alt-b and Alt-f for this, apparently.

**Comment by slingamn** [comment]
Alt-b and Alt-f in xterm/urxvt produce `\x1bb` and `\x1bf` respectively.

**Comment by slingamn** [comment]
Someone told me that in general with xterm, combining alt with a key will produce an additional `\x1b` in front of whatever sequence that key would normally produce. This explains the alt-right and alt-left behaviors.

**Comment by wader** [comment]
Sorry for delay also, out traveling a bit. Think i'm using "Natural text editing" with iterm2 also. Nice research and it sounds like you have figure out how to make `opt|alt+left/right` work in most popular terminals?

**Comment by wader** [comment]
🥳 planning a new release soonish?

**Comment by wader** [comment]
rc1 seems to work fine and all tests pass, but the readline-parts are not exercised much

**Comment by slingamn** [comment]
Nice, I felt pretty confident so I went ahead and tagged `v0.1.2` :-)
