### ISSUE TITLE
Can it support pipe line input ?  echo "pipeinput" | ./readline-cli

### ISSUE THREAD

**Issue by johnwmail** [ergochat/readline#62]
![image](https://github.com/ergochat/readline/assets/1752235/8e86b645-606e-4584-bd0e-2c7b47632dae)

**Comment by slingamn** [comment]
What is the question exactly? Your screenshot seems to show readline working as expected with non-terminal input.

**Comment by wader** [comment]
I think related to https://github.com/chzyer/readline/issues/234

**Comment by slingamn** [comment]
Oh, that makes sense, the ask is for the program to continue executing? [expect(1)](https://linux.die.net/man/1/expect) is the normal workaround for this, it works with both our fork and upstream.

**Comment by slingamn** [comment]
```
#!/usr/bin/expect -f

spawn ./readline-demo
send "pipeinput\n"
interact
```

produces

```
$ ./expect-demo 
spawn ./readline-demo
pipeinput
» pipeinput
2024/06/16 05:08:04 you said: "pipeinput"
» 
```

Integrating this directly into readline is out of scope.

**Comment by johnwmail** [comment]
Yes,  expect work as what I want, thank you.

> Integrating this directly into readline is out of scope. (YES, I know)

BTW, I am curiously,  why expect can catch/hold the readline-cli,   but console (run readline-cli directly) cannot?
Pls feel free to share the concept , I want learning this ( to integrate it to my golang-cli) , thank you.

**Comment by johnwmail** [comment]
My golang-cli is will simply call fmt.Scanln and ask the user input login/pass as variable while the cli running.
In the meantime, the cli can either open file, everything work fine,

Until I want make it support either open file or  read the pipeline input,  the pipeline input break the fmt.Scanln  

(like this:   echo "filename" |  cli     or    cli -f filename)  and while the cli running , it will ask user input login/pass
